# Generated by Django 6.1 on 2026-08-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('university', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=50)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('career_interest', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('fullstack', 'Full Stack Development'), ('qa', 'QA / Software Testing'), ('data', 'Data Science'), ('ai', 'Artificial Intelligence'), ('uiux', 'UI/UX Design'), ('cybersecurity', 'Cybersecurity'), ('other', 'Other')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
